<a href="https://colab.research.google.com/github/unknownguy24/Deep-Learning/blob/main/Word_Embedding.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from tensorflow.keras.preprocessing.text import one_hot

In [2]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [3]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [4]:
### Vocabulary size
voc_size=10000   #tells us the size of the dictionary which will tell us the index of the word

In [5]:
#One Hot Representation
onehot_repr=[one_hot(words,voc_size)for words in sent] #gives an index to each word
print(onehot_repr)

[[6078, 4795, 6002, 7745], [6078, 4795, 6002, 7109], [6078, 9208, 6002, 3432], [7317, 3194, 1404, 3013, 4721], [7317, 3194, 1404, 3013, 3276], [5801, 6078, 601, 6002, 3814], [474, 6989, 5477, 3013]]


In [6]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences  #makes sure the size i.e number of words in the sentence is same
from tensorflow.keras.models import Sequential
import numpy as np

In [7]:
sent_length=8   #maximum sentence size setting
embedded_docs=pad_sequences(onehot_repr,padding='pre',maxlen=sent_length) #as max size is 8, padding is applied as pre meaning out of 8 words if 4 are present before the 4 all will have 0 index
print(embedded_docs)

[[   0    0    0    0 6078 4795 6002 7745]
 [   0    0    0    0 6078 4795 6002 7109]
 [   0    0    0    0 6078 9208 6002 3432]
 [   0    0    0 7317 3194 1404 3013 4721]
 [   0    0    0 7317 3194 1404 3013 3276]
 [   0    0    0 5801 6078  601 6002 3814]
 [   0    0    0    0  474 6989 5477 3013]]


In [9]:
model=Sequential()
model.add(Embedding(voc_size,10,input_length=sent_length)) #we have taken 10 dimensions(features)
model.compile('adam','mse')

In [10]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 8, 10)             100000    
                                                                 
Total params: 100,000
Trainable params: 100,000
Non-trainable params: 0
_________________________________________________________________


In [11]:
print(model.predict(embedded_docs)) #to see how our words are converted to vectors i.e the Feature Representation

1/1 [==============================] - 0s 170ms/step
[[[-3.1200275e-03 -3.8783170e-02  1.4863126e-03  1.7725315e-02
    1.7509881e-02 -4.4702459e-02  3.0547861e-02  8.1213117e-03
   -1.5148841e-02 -1.7340936e-02]
  [-3.1200275e-03 -3.8783170e-02  1.4863126e-03  1.7725315e-02
    1.7509881e-02 -4.4702459e-02  3.0547861e-02  8.1213117e-03
   -1.5148841e-02 -1.7340936e-02]
  [-3.1200275e-03 -3.8783170e-02  1.4863126e-03  1.7725315e-02
    1.7509881e-02 -4.4702459e-02  3.0547861e-02  8.1213117e-03
   -1.5148841e-02 -1.7340936e-02]
  [-3.1200275e-03 -3.8783170e-02  1.4863126e-03  1.7725315e-02
    1.7509881e-02 -4.4702459e-02  3.0547861e-02  8.1213117e-03
   -1.5148841e-02 -1.7340936e-02]
  [-4.8430838e-02  3.2295059e-02 -2.2323156e-02 -4.8302997e-02
   -3.6034666e-02 -2.0707905e-02 -3.5980187e-02  4.4736266e-03
   -4.6180129e-02 -2.5957216e-02]
  [-7.0332885e-03 -3.1237826e-03 -9.0912804e-03  2.3580167e-02
   -3.6695220e-02  2.3775529e-02 -9.7562075e-03  9.0727434e-03
    2.1119006e-03  3.

In [12]:
embedded_docs[0] #before passing through embeded layer

array([   0,    0,    0,    0, 6078, 4795, 6002, 7745], dtype=int32)

In [13]:
print(model.predict(embedded_docs)[0])   #each word having 10 dimension and creating a vector

1/1 [==============================] - 0s 30ms/step
[[-0.00312003 -0.03878317  0.00148631  0.01772531  0.01750988 -0.04470246
   0.03054786  0.00812131 -0.01514884 -0.01734094]
 [-0.00312003 -0.03878317  0.00148631  0.01772531  0.01750988 -0.04470246
   0.03054786  0.00812131 -0.01514884 -0.01734094]
 [-0.00312003 -0.03878317  0.00148631  0.01772531  0.01750988 -0.04470246
   0.03054786  0.00812131 -0.01514884 -0.01734094]
 [-0.00312003 -0.03878317  0.00148631  0.01772531  0.01750988 -0.04470246
   0.03054786  0.00812131 -0.01514884 -0.01734094]
 [-0.04843084  0.03229506 -0.02232316 -0.048303   -0.03603467 -0.02070791
  -0.03598019  0.00447363 -0.04618013 -0.02595722]
 [-0.00703329 -0.00312378 -0.00909128  0.02358017 -0.03669522  0.02377553
  -0.00975621  0.00907274  0.0021119   0.03254235]
 [ 0.02579541  0.04288323 -0.0071308   0.03411994 -0.04346092 -0.04035962
   0.03881076 -0.02784557 -0.04514198  0.03329289]
 [ 0.0176561   0.03827466 -0.00314825 -0.01707496 -0.00927894  0.01245864

In [14]:
#This code shows how a vector representaiton i.e a feature representation is formed and nothing else